ci(workflows): ⚙️ atualizar referências de workflows reutilizáveis
* Renomear o repositório de workflows de 'actions-flow' para 'reusable-workflows

diff --git a/.github/workflows/cd-pull-request.yml b/.github/workflows/cd-pull-request.yml
--- a/.github/workflows/cd-pull-request.yml
+++ b/.github/workflows/cd-pull-request.yml
@@ -221,7 +221,40 @@ jobs:
       if: needs.resolve-branch.outputs.skip != 'true'
       # working-directory: ${{ steps.path.outputs.value }}
       run: |
-        echo "## 📝 PR Body"
+        if [ -n "${{ inputs.pr_body_path }}" ]; then
+          PR_BODY_PATH="${{ inputs.pr_body_path }}"
+          log "Usando atributo \`pr_body_path\`: $PR_BODY_PATH"
+
+          if [ ! -f "$PR_BODY_PATH" ]; then
+            fail "PR body file \`not found\`: $PR_BODY_PATH"
+          fi          
+          PR_TEMPLATE="$(cat $PR_BODY_PATH)"
+        elif [ -n "${{ inputs.pr_body }}" ]; then 
+          log "Usando atributo \`pr_body\`"
+          PR_TEMPLATE="${{ inputs.pr_body  }}"
+        fi
+
+        if ! [ -v PR_TEMPLATE ]; then
+          log "Usando template padrão"
+          PR_TEMPLATE=$(cat "${{ env.REUSABLE_PATH }}/.github/templates/pr_template.md")
+        fi
+
+        STATUS_DISPLAY="➖"
+        COVERAGE_BLOCK="missing"
+        HAS_COVERAGE=${{ needs.read-quality.outputs.hasCoverage }}
+
+        # Verifica se o template contém a chave para bloco de qualidade
+        if [[ "$PR_TEMPLATE" == *"{{QUALITY_GATE_RESULT}}"* ]]; then
+          TITLE_BLOCK="📊 Cobertura de Testes"
+
+          if [[ "$HAS_COVERAGE" == "true" ]]; then
+            COVERAGE_BLOCK="found"
+          else
+            COVERAGE_BLOCK="not-found"
+          fi
+        fi
+
+        log "COVERAGE_BLOCK: $COVERAGE_BLOCK"
 
     - name: 📜 Create or Update Pull Request
       id: create-pr
